# Generated by Django 5.0.1 on 2024-01-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationAndLogin', '0002_alter_user_datetimecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
