# Generated by Django 4.2.8 on 2024-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationAndLogin', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='psswd',
            field=models.CharField(max_length=90),
        ),
    ]
