# Generated by Django 4.2.8 on 2024-01-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendManager', '0002_remove_friend_request_datesent_friend_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_relation',
            old_name='usrOneId',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='user_relation',
            old_name='usrTwoId',
            new_name='user2',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='status',
        ),
    ]
