# Generated by Django 4.2.8 on 2024-01-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0002_remove_marker_datetimecreated_marker_timecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='hasDesc',
        ),
        migrations.AddField(
            model_name='marker',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(default='No Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
