# Generated by Django 4.2.8 on 2024-01-24 01:36

from django.db import migrations, models
import django.db.models.deletion
import markerManager.models


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0004_delete_marker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='folderPath',
            field=models.CharField(default=markerManager.models.generate_uuid, max_length=36),
        ),
        migrations.CreateModel(
            name='MARKER_IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderPath', models.CharField(default=markerManager.models.generate_uuid, max_length=36)),
                ('markerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgToMarkerId', to='markerManager.marker')),
            ],
        ),
    ]
