# Generated by Django 5.0.1 on 2024-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0006_marker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=models.CharField(default='Default', max_length=10),
        ),
    ]
