# Generated by Django 4.2.8 on 2024-01-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapManager', '0001_initial'),
        ('registrationAndLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MARKER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.CharField(max_length=40)),
                ('imageCount', models.IntegerField(default=0)),
                ('hasDesc', models.BooleanField(default=False)),
                ('dateTimeCreated', models.DateTimeField()),
                ('mapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markerToMapId', to='mapManager.map')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markerToUserId', to='registrationAndLogin.user')),
            ],
        ),
    ]
