# Generated by Django 4.2.8 on 2024-01-23 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='dateTimeCreated',
        ),
        migrations.AddField(
            model_name='marker',
            name='timeCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='marker',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MARKER_IMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markerImageToMarker', to='markerManager.marker')),
            ],
        ),
    ]
