# Generated by Django 4.2.8 on 2024-01-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0003_remove_marker_hasdesc_marker_desc_marker_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MARKER_IMAGE',
        ),
    ]
