# Generated by Django 4.2.8 on 2024-02-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markerManager', '0005_marker_folderpath_marker_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='color',
            field=models.CharField(default='orange', max_length=10),
        ),
    ]
