# Generated by Django 4.2.8 on 2024-01-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrationAndLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_RELATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('usrOneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrRelToUser1', to='registrationAndLogin.user')),
                ('usrTwoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrRelToUser2', to='registrationAndLogin.user')),
            ],
        ),
        migrations.CreateModel(
            name='FRIEND_REQUEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateTimeField()),
                ('recId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverToUser', to='registrationAndLogin.user')),
                ('sendId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderToUser', to='registrationAndLogin.user')),
            ],
        ),
    ]
