# Generated by Django 4.2.8 on 2024-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='dateSent',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
