# Generated by Django 4.2.8 on 2024-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('psswd', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateTimeCreated', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('mapCount', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=15)),
            ],
        ),
    ]
